sudo: required

language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8

script:
  - make debug
  - sudo mknod /dev/net/tap c 10 200
  - sudo ./lvl-ip
